<?php
/*
Plugin Name: BP Widget Cache
Description: Cache the output of BuddyPress widgets using site transients.
Version: 0.1-alpha
Author: r-a-y
Author URI: http://profiles.wordpress.org/r-a-y
License: GPLv2 or later
*/

// Exit if accessed directly
if ( !defined( 'ABSPATH' ) ) exit;

/**
 * Only load the plugin code if BuddyPress is activated.
 */
function bp_widget_cache_include() {
	require( dirname( __FILE__ ) . '/bp-widget-cache.php' );
}
add_action( 'bp_include', 'bp_widget_cache_include' );

/**
 * Deactivation hook.
 *
 * Delete all cache generated by BP Widget Cache.
 */
function bp_widget_cache_deactivation() {
	bp_widget_cache_invalidate_all();
}
register_deactivation_hook( __FILE__, 'bp_widget_cache_deactivation' );